### ISSUE TITLE
Can I replace your MELPA recipe with my go-impl package ?

### ISSUE THREAD

**Issue by syohex** [dominikh/go-impl.el#2]
I didn't know your that your go-impl package already registered MELPA and I created same name package. I implemented completion of package names and interface names as below. This feature is useful for users.

![my-go-impl](https://github.com/syohex/emacs-go-impl/raw/master/image/go-impl.gif)

I have implemented feature of your package https://github.com/syohex/emacs-go-impl/pull/3 (not merged yet).

**Comment by dominikh** [comment]
Do you feel strongly about replacing my package, instead of merging your changes into mine?

**Comment by syohex** [comment]
Yes.

**Comment by dominikh** [comment]
Fine, go ahead, one less package for me to maintain. /cc me on the PR to MELPA to I can sign off on it.

**Comment by syohex** [comment]
Thanks!!!!
